### ISSUE TITLE
Panic in main.go:1081

### ISSUE THREAD

**Issue by BaardBouvet** [sesam-io/sesam#14]
When running sesam test, I get the following error message:
```
M-C02QN6HEG8WP:node tarjei.skrede$ sesam test
Node config replaced with local config.
panic: runtime error: invalid memory address or nil pointer dereference
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1255c1c]

goroutine 1 [running]:
main.assert2xx(0x0, 0xc4204ae000, 0x0)
/home/travis/gopath/src/github.com/sesam-io/sesam/main.go:1081 +0x2c
main.(*connection).doRequest(0xc4205003c0, 0xc4204ae000, 0xc420496400, 0x32, 0x0)
/home/travis/gopath/src/github.com/sesam-io/sesam/main.go:1056 +0x4c
main.(*connection).deleteSystem(0xc4205003c0, 0x12f01e4, 0x9, 0x4, 0x0)
/home/travis/gopath/src/github.com/sesam-io/sesam/main.go:1249 +0x200
main.removeDefaultScheduler(0xc4205003c0, 0xc420052310, 0xc420090d80)
/home/travis/gopath/src/github.com/sesam-io/sesam/main.go:737 +0x56
panic(0x129dfc0, 0x1440990)
/home/travis/.gimme/versions/go1.8.3.linux.amd64/src/runtime/panic.go:489 +0x2cf
main.assert2xx(0x0, 0xc4204ae600, 0x0)
/home/travis/gopath/src/github.com/sesam-io/sesam/main.go:1081 +0x2c
main.(*connection).doRequest(0xc4205003c0, 0xc4204ae600, 0xc420496980, 0x39, 0x0)
/home/travis/gopath/src/github.com/sesam-io/sesam/main.go:1056 +0x4c
main.(*connection).getProxyJson(0xc4205003c0, 0x12f01e4, 0x9, 0x0, 0x0, 0x127bd40, 0xc4204d8058, 0x0, 0x0)
/home/travis/gopath/src/github.com/sesam-io/sesam/main.go:1312 +0x286
main.run(0x0, 0x0)
/home/travis/gopath/src/github.com/sesam-io/sesam/main.go:204 +0x64d
main.test(0x7fff5fbffca6, 0x4)
/home/travis/gopath/src/github.com/sesam-io/sesam/main.go:229 +0x55
main.main()
/home/travis/gopath/src/github.com/sesam-io/sesam/main.go:110 +0x5e9
```

**Comment by BaardBouvet** [comment]
Fixed in #13
