### ISSUE TITLE
'sesam test' fails with http status code 500

### ISSUE THREAD

**Issue by ga-hegsvold** [sesam-io/sesam#7]
```
$ sesam test
Node config replaced with local config.
test failed: failed to start scheduler: expected http status code 2xx, got: 500
```

node.log

```
2017-08-31 14:31:44,422 - CP Server Thread-27 - lake.node.webapp - ERROR - Exception on /api/systems/scheduler/proxy/start [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connection.py", line 142, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/util/connection.py", line 91, in create_connection
    raise err
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/util/connection.py", line 81, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 578, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 362, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connection.py", line 167, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connection.py", line 151, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x7f9f3ada0198>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 403, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/connectionpool.py", line 623, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/requests/packages/urllib3/util/retry.py", line 281, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='scheduler', port=5000): Max retries exceeded with url: /start?delete_datasets=true&reset_pipes=true (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f9f3ada0198>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/decorator.py", line 118, in wrapper
    response_container = function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/validation.py", line 286, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/produces.py", line 94, in wrapper
    response = function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/decorator.py", line 98, in wrapper
    operation_handler_result = function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/connexion/decorators/parameter.py", line 161, in wrapper
    return function(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/lake/node/webapp/api/systems.py", line 746, in post_microservice_proxy
    r = requests.post(url, data=flask.request.form, params=flask.request.args, stream=True)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 111, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 57, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 467, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='scheduler', port=5000): Max retries exceeded with url: /start?delete_datasets=true&reset_pipes=true (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7f9f3ada0198>: Failed to establish a new connection: [Errno 111] Connection refused',))
2017-08-31 14:31:55,797 - Thread-8 - lake.task.backuptask - INFO - Performing backup..
2017-08-31 14:32:31,970 - Thread-8 - lake.task.backuptask - INFO - Backup complete. Purging old backups...
2017-08-31 14:32:32,814 - Thread-8 - lake.task.backuptask - INFO - Purging old backups complete
2017-08-31 14:35:17,266 - Thread-36 - lake.task.datasync - INFO - Pumping 'system:download-jwt-revocation'
...
```

**Comment by BaardBouvet** [comment]
The client will now wait until the 500s disappear (the microservice is running, but not responding to requests yet)
